version: 2.1
orbs:
  node: circleci/node@1.1.6
  heroku: circleci/heroku@0.0.10
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
workflows:
    heroku_deploy:
      jobs:
        - build
        - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
            requires:
              - build
            filters:
              branches:
                only: master